# Generated by Django 5.1.4 on 2024-12-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="releving_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("mechanic", "Mechanic"),
                    ("accountant", "Accountant"),
                    ("helper", "Helper"),
                    ("sales", "Sales"),
                    ("finance", "Finance"),
                ],
                default="helper",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeShortLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("leave_start", models.TimeField()),
                ("leave_end", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_leaves",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Short Leave",
                "verbose_name_plural": "Employee Short Leaves",
                "ordering": ["date", "leave_start"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("On Leave", "On Leave"),
                        ],
                        default="Absent",
                        max_length=10,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
    ]
