# Generated by Django 5.1.4 on 2024-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_hire_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeshortleave",
            name="approved",
            field=models.CharField(
                choices=[
                    ("Approve", "Approve"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
